import 'package:flutter/material.dart';

/// Complete Material 3 color palette for AskMe HUMG.
///
/// Base colors extracted from the official HUMG logo:
///   - Dark Navy  (#1A3A8C) — outer ring, primary brand color
///   - Sky Blue   (#2D9BD8) — inner globe, accent/interactive color
///   - White      (#FFFFFF) — logo text and icon lines
///
/// Extended tokens generated by Stitch (26-02-2026) to cover all
/// Material 3 roles needed for a complete dark UI implementation.
abstract final class AppColors {
  // ---------------------------------------------------------------------------
  // Backgrounds & Surfaces
  // ---------------------------------------------------------------------------

  /// Main app background — near-black deep navy.
  static const Color background = Color(0xFF0A0D1A);

  /// Default card / sheet surface.
  static const Color surface = Color(0xFF0D1B3E);

  /// Elevated surface (modals, bottom sheets, drawers, input fill).
  static const Color surfaceElevated = Color(0xFF162347);

  /// Slightly different surface for alternating sections.
  static const Color surfaceVariant = Color(0xFF11224D);

  // ---------------------------------------------------------------------------
  // Brand — HUMG Navy (Primary — non-interactive)
  // ---------------------------------------------------------------------------

  /// Primary brand color — HUMG dark navy (outer ring of logo).
  /// Use for branding only, NOT for interactive elements.
  static const Color primary = Color(0xFF1A3A8C);

  /// Lighter tint of primary — hover / pressed states.
  static const Color primaryLight = Color(0xFF2A4FA8);

  /// Darker shade of primary — active / focused states.
  static const Color primaryDark = Color(0xFF102570);

  // ---------------------------------------------------------------------------
  // Brand — HUMG Sky Blue (Accent / ALL Interactive Elements)
  // ---------------------------------------------------------------------------

  /// Accent color — HUMG sky blue (inner globe of logo).
  /// Use for: ALL interactive elements — buttons, FAB, active tabs, links, icons.
  static const Color accent = Color(0xFF2D9BD8);

  /// Text/icon color on top of accent (#2D9BD8) backgrounds.
  static const Color onAccent = Color(0xFFFFFFFF);

  /// Lighter tint of accent — chip backgrounds, badge fills.
  static const Color accentLight = Color(0xFF4DB8F0);

  /// Darker shade of accent — pressed state on accent elements.
  static const Color accentDark = Color(0xFF1A7AAF);

  // ---------------------------------------------------------------------------
  // Text
  // ---------------------------------------------------------------------------

  /// Primary text — white, high emphasis.
  static const Color textPrimary = Color(0xFFFFFFFF);

  /// Secondary text — muted blue-gray, medium emphasis.
  static const Color textSecondary = Color(0xFF7FA8C9);

  /// Disabled / placeholder text — low emphasis.
  static const Color textDisabled = Color(0xFF3D5A7A);

  /// Placeholder text inside input fields.
  static const Color inputHint = Color(0xFF5E7E9E);

  // ---------------------------------------------------------------------------
  // Border & Divider
  // ---------------------------------------------------------------------------

  /// Default border / input border.
  static const Color border = Color(0xFF1E3A6E);

  /// Subtle divider — between list items.
  static const Color divider = Color(0xFF152850);

  // ---------------------------------------------------------------------------
  // Overlay & Scrim
  // ---------------------------------------------------------------------------

  /// Semi-transparent overlay (70% black) behind bottom sheets and dialogs.
  static const Color scrim = Color(0xB3000000);

  /// Semi-transparent white (10%) for pressed card states.
  static const Color cardOverlay = Color(0x1AFFFFFF);

  // ---------------------------------------------------------------------------
  // Shimmer (Skeleton Loading)
  // ---------------------------------------------------------------------------

  /// Base color for skeleton loading cards.
  static const Color shimmerBase = Color(0xFF162347);

  /// Highlight sweep color for shimmer animation.
  static const Color shimmerHighlight = Color(0xFF213363);

  // ---------------------------------------------------------------------------
  // Badge (Notification Dot)
  // ---------------------------------------------------------------------------

  /// Notification badge dot background (unread count).
  static const Color badgeBackground = Color(0xFFEF4444);

  /// Text color on notification badge.
  static const Color badgeText = Color(0xFFFFFFFF);

  // ---------------------------------------------------------------------------
  // Anonymous Badge
  // ---------------------------------------------------------------------------

  /// Anonymous chip/badge background.
  static const Color anonymousBadge = Color(0xFF162347);

  /// Foreground text color on the anonymous lock chip.
  static const Color anonymousBadgeText = Color(0xFF7FA8C9);

  // ---------------------------------------------------------------------------
  // Tab
  // ---------------------------------------------------------------------------

  /// Subtle background for unselected tabs.
  static const Color tabInactiveBackground = Color(0xFF0D1B3E);

  // ---------------------------------------------------------------------------
  // Semantic — Success
  // ---------------------------------------------------------------------------

  /// Success — positive feedback, sent confirmation text/icon.
  static const Color success = Color(0xFF22C55E);

  /// Snackbar / toast background for success state.
  static const Color successBackground = Color(0xFF064E3B);

  // ---------------------------------------------------------------------------
  // Semantic — Warning & Error
  // ---------------------------------------------------------------------------

  /// Warning — rate limit warnings, moderation notices.
  static const Color warning = Color(0xFFF59E0B);

  /// Error — validation errors, failed submissions, delete actions.
  static const Color error = Color(0xFFEF4444);

  // ---------------------------------------------------------------------------
  // Misc
  // ---------------------------------------------------------------------------

  /// Like / heart icon — filled state.
  static const Color like = Color(0xFFEF4444);

  /// Fully transparent.
  static const Color transparent = Colors.transparent;
}
